name: Run Demo on Push

on:
  push:
    branches:
      - '**'   # Match all branches
  workflow_dispatch:

jobs:
  run-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Check script exists
      #   run: test -f ./run-demo.sh

      # - name: Make script executable
      #   run: chmod +x run-demo.sh

      # - name: Run the demo script
      #   run: ./run-demo.sh

      # - name: Upload results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: |
      #       ./demo/results/test_start.txt
      #       ./demo/results/test_end.txt
      #       ./demo/demo/dbt-spark-demo.ipynb

      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install  --upgrade pip
      #     python -m pip install  --no-cache-dir "uv>=0.1.30,<0.2"

      # - name: Install jupyter notebook
      #   run: |
      #     uv venv my_env
      #     . ./my_env/bin/activate          
      #     uv pip install notebook

      # - name: Install Quarto
      #   run: |
      #     curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
      #     sudo dpkg -i quarto-linux-amd64.deb
      #     quarto --version

      # - name: Render notebook and copy rendered output to docs
      #   run: |
      #     quarto render ./demo/dbt-spark-demo.ipynb
      #     cp ./demo/dbt-spark-demo.html ./docs/index.htmlgit s
          
      # - name: Upload results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: |
      #       ./index.html

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs

      - name: Copy index.html to docs/
        run: |
          mkdir -p docs
          cp index.html docs/index.html

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add docs/
          git commit -m "Update docs" || echo "No changes to commit"
          git push
